name: landmug_login
description: Figmaâ†’Flutter ë¡œê·¸ì¸ í™”ë©´
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ UI ê´€ë ¨
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  barcode_widget: ^2.0.4

  # ðŸ”¹ Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
